# Site
repository: https://github.com/GeorgiosPapandroulidakis
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Georgios Papandroulidakis
title: Researcher
email: gpapandr@ed.ac.uk
website: https://georgiospapandroulidakis.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  GeorgiosPapandroulidakis
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: georgios-papandroulidakis-150105196
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: LinkedIn
#  icon: fas fa-globe
#  url: ---
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/GP_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  (Under construction ...)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: (Under construction ...)
        link: https://github.com/GeorgiosPapandroulidakis
        # link_text: Project Website
        additional_links:
          - title:  https://github.com/GeorgiosPapandroulidakis
            icon: fab fa-github
            url: https://github.com/GeorgiosPapandroulidakis
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          ...

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Edinburgh (UK)
        link: https://cef.eng.ed.ac.uk/about/our-team/georgios-papandroulidakis
        link_text: Centre for Electronics Frontiers Research Group, IMNS, School of Engineering
        sub_title: Post-Doctoral Research Associate
        caption: May 2022 - Present
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Research and development of In-Memory Computing Architectures based on hybrid circuit design (emerging memory technologies + CMOS). Custom analogue and mixed-signal IC design and implementation, PCB hardware prototyping, hardware testing enginnering.

    #layout: list # Type of content section (list/text)
    #content:
      - layout: left
        title: University of Southampton (UK)
        link: ...
        link_text: ...
        sub_title: Post-Doctoral Research Fellow
        caption: September 2021 - April 2022
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Technology consultation for emerging computing technologies with focus on novel AI/ML integration with systems. Designing of evaluation framework for applying AI/ML and other novel technologies to existing systems.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Southampton (UK)
        caption: 2017 - 2021
        sub_title: PhD in Electronics and Computer Science
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Research and design on analogue and mixed-signal circuits and systems based on emerging memory technologies. Focus on RRAM-based Threshold Logic Gates, Winner Take All and Dot Product inference engines circuits and systems. Hardware prototyping, on-wafer measurements and device characterisation, circuits and systems design and testing.

    #layout: list # Type of content section (list/text)
    #content:
      - layout: left
        title: Democritus University of Thrace (Greece)
        caption: 2015 - 2017
        sub_title: MSc in Electronics and Computer Science
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          MSc thesis on RRAM-based circuits, sytems and computer architectures.

    #layout: list # Type of content section (list/text)
    #content:
      - layout: left
        title: Democritus University of Thrace (Greece)
        caption: 2009 - 2015
        sub_title: Diploma-MEng in Electronics and Computer Science
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Electrical and electronics engineering. Diploma thesis on emerging memory devices and hybrid circuit design.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my research interests in circuits and systems some of my other interests and hobbies are:
      - Python notebooks for data processing and ANN implementations
      - Electrical and electronics for music
      - ...


# Footer
footer_show_references: true
references_title: ...

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
